'use strict';
const AdvancedMath={
 compute(type,a,b){let rows=[],value=0;const row=(z,e,v)=>rows.push([z,e,v]);
 if(type==='broadcast'){value=a*a;row('输入形状','Input shapes',`(${a},1) − (${a},)`);row('广播结果形状','Broadcast result',`(${a},${a})`);row('错误残差元素数','Incorrect residual element count',value);row('正确一维残差元素数','Correct 1D residual element count',a)}
 if(type==='bayes'){let p=a/100,t=b/100,tp=10000*p*t,fp=10000*(1-p)*.05;value=100*tp/(tp+fp);row('真阳性期望数量','Expected true positives',tp);row('假阳性期望数量','Expected false positives',fp);row('阳性总数','Total positives',tp+fp);row('阳性后验（%）','Posterior given positive (%)',value)}
 if(type==='uncertainty'){value=b/Math.sqrt(a);row('独立样本数','Independent sample count',a);row('样本标准差','Sample SD',b);row('均值标准误','Mean standard error',value);row('样本量变为四倍的标准误','SE with four times the sample size',value/2)}
 if(type==='projection'){let t=a*Math.PI/180,e=[Math.cos(t),Math.sin(t)],z=3*e[0]+2*e[1],p=e.map(v=>v*z),r=[3-p[0],2-p[1]];value=z;row('单位方向','Unit direction',e.map(v=>v.toFixed(4)).join(', '));row('标量投影','Scalar projection',z);row('投影向量','Projection vector',p.map(v=>v.toFixed(4)).join(', '));row('残差与方向内积','Residual dot direction',r[0]*e[0]+r[1]*e[1]);return {value,rows,projection:p}}
 if(type==='pca'){let t=a*Math.PI/180;value=2+Math.sin(2*t);row('协方差矩阵','Covariance matrix','[[2,1],[1,2]]');row('方向方差 eᵀCe','Directional variance eᵀCe',value);row('总方差','Total variance',4);row('该方向方差占比','Fraction of total variance',value/4);row('最大特征值','Largest eigenvalue',3)}
 if(type==='svd'){let s=[4,3,2,1],energy=s.map(x=>x**4),total=energy.reduce((x,y)=>x+y,0);value=100*energy.slice(a).reduce((x,y)=>x+y,0)/total;row('奇异值','Singular values','4, 3, 2, 1');row('Gram 总平方能量','Total squared Gram energy',total);row('保留秩','Retained rank',a);row('相对平方误差（%）','Relative squared error (%)',value);return {value,rows,bars:energy}}
 if(type==='chain'){let z=a*b,act=Math.tanh(z);value=(act-1)*(1-act*act)*b;row('线性输出 z=wx','Linear output z=wx',z);row('激活 a=tanh(z)','Activation a=tanh(z)',act);row('损失 (a−1)²/2','Loss (a−1)²/2',(act-1)**2/2);row('梯度 dL/dw','Gradient dL/dw',value)}
 if(type==='train'){let w=3;row('初始 w','Initial w',w);for(let i=1;i<=b;i++){w-=a*2*w;row('第 '+i+' 步损失','Step '+i+' loss',w*w)}value=w*w;row('最终损失','Final loss',value)}
 if(type==='init'){let sd=b/Math.sqrt(a);value=a*sd*sd;row('输入通道数 C','Input channels C',a);row('权重标准差','Weight SD',sd);row('输入方差','Input variance',1);row('输出方差','Output variance',value)}
 if(type==='conv'){value=Math.floor((32+2-a)/b)+1;row('输入高宽 / padding','Input size / padding','32×32 / 1');row('卷积核 / stride','Kernel / stride',`${a}×${a} / ${b}`);row('输出高宽','Output height and width',`${value}×${value}`);row('含偏置参数量（3→8）','Biased parameter count (3→8)',8*3*a*a+8)}
 if(type==='freeze'){let head=1024*a+a;value=head+b*1000000;row('示例骨干参数（非 ResNet 实数）','Illustrative backbone count (not actual ResNet)',1000000);row('分类头参数','Head parameters',head);row('骨干参数是否训练','Train backbone parameters?',b?'1':'0');row('可训练参数','Trainable parameters',value);row('总参数','Total parameters',1000000+head)}
 if(type==='embedding'){value=Math.cos(a*Math.PI/180);row('两个单位向量夹角','Angle between unit vectors',a);row('余弦相似度','Cosine similarity',value);row('平方欧氏距离','Squared Euclidean distance',2-2*value)}
 if(type==='neighbors'){let x=[0,1,2,8,9],r=x.map((v,i)=>({v,i,d:Math.abs(v-2)})).filter(v=>v.i!==2).sort((x,y)=>x.d-y.d);value=r[a-1].d;row('查询点','Query',2);row('近邻值','Neighbor values',r.slice(0,a).map(x=>x.v).join(', '));row('第 k 个近邻距离','Distance to kth neighbor',value);row('实验范围','Experiment scope','kNN graph only; no UMAP optimization')}
 if(type==='macro'){let y=[0,0,0,0,1,1,1,1],p=[.05,.2,.4,.65,.3,.55,.75,.9],pred=p.map(x=>+(x>=a)),tp=0,fp=0,fn=0,tn=0;y.forEach((v,i)=>{if(v&&pred[i])tp++;else if(!v&&pred[i])fp++;else if(v&&!pred[i])fn++;else tn++});let f1=2*tp/(2*tp+fp+fn)||0,f0=2*tn/(2*tn+fp+fn)||0;value=(f1+f0)/2;row('混淆计数 TP,FP,FN,TN','Confusion counts TP,FP,FN,TN',[tp,fp,fn,tn].join(', '));row('正类 F1','Positive-class F1',f1);row('负类 F1','Negative-class F1',f0);row('宏平均 F1','Macro F1',value);row('准确率','Accuracy',(tp+tn)/8)}
 if(type==='knn_deep'){let points=[[0,0,0],[1,10,0],[2,800,1],[3,900,1],[4,1000,1]],q=[1.5,450];let list=points.map((p,i)=>({i,label:p[2],distance:Math.hypot((p[0]-q[0])/(b?4:1),(p[1]-q[1])/(b?1000:1))})).sort((a,b)=>a.distance-b.distance||a.i-b.i);let votes=list.slice(0,a).reduce((s,p)=>s+p.label,0);value=+(votes>a/2);row('前 k 个训练点索引','Nearest training indices',list.slice(0,a).map(p=>p.i).join(', '));row('类 1 票数','Votes for class 1',votes);row('预测标签（并列取 0）','Prediction (ties choose 0)',value);row('缩放','Scaling',b?'ranges [4,1000]':'none')}
 if(type==='audit'){value=a-b;row('总可用分钟','Total available minutes',a);row('预留检查分钟','Reserved check minutes',b);row('可用于作答分钟','Minutes available for solving',value);row('最后检查','Final check','Restart → Run all → Check output contract')}
 return {value,rows};
 }
};
const ADVANCED_LABS={
 broadcast:[['样本数 N','Samples N',2,20,1,8],null,'错误广播后的残差元素数','Element count after incorrect broadcasting'],
 bayes:[['先验（%）','Prior (%)',.1,50,.1,1],['检出率（%）','Sensitivity (%)',10,100,1,90],'阳性后验（%），误报率固定 5%','Positive posterior (%), with false-positive rate fixed at 5%'],
 uncertainty:[['独立样本数','Independent sample size',4,400,1,36],['样本标准差','Sample SD',1,30,1,12],'均值标准误','Standard error of the mean'],
 projection:[['方向角（度）','Direction angle (degrees)',0,180,1,45],null,'x=(3,2) 的标量投影','Scalar projection of x=(3,2)'],
 pca:[['方向角（度）','Direction angle (degrees)',0,180,1,45],null,'协方差 [[2,1],[1,2]] 的方向方差','Directional variance for covariance [[2,1],[1,2]]'],
 svd:[['保留秩 r','Retained rank r',1,4,1,2],null,'Gram 矩阵相对平方误差（%）','Gram relative squared error (%)'],
 chain:[['权重 w','Weight w',-2,2,.1,0],['输入 x','Input x',.5,3,.5,2],'y=1 时 dL/dw','dL/dw when y=1'],
 train:[['学习率','Learning rate',0,1.2,.05,.1],['更新次数','Updates',1,12,1,5],'J(w)=w²，w 初值 3：最终损失','Final loss for J(w)=w², initial w=3'],
 init:[['输入维数 C','Input dimension C',1,100,1,16],['标准差倍数','SD multiplier',.5,2,.25,1],'输入方差 1 时的输出方差','Output variance for input variance 1'],
 conv:[['卷积核边长','Kernel size',1,7,1,3],['步幅','Stride',1,4,1,2],'32×32 输入、padding=1：输出边长','Output size for 32×32 input, padding=1'],
 freeze:[['类别数','Class count',2,20,1,5],['训练骨干：0 否 / 1 是','Train backbone: 0 no / 1 yes',0,1,1,0],'示例模型的可训练参数数','Trainable parameters in the illustrative model'],
 embedding:[['夹角（度）','Angle (degrees)',0,180,1,60],null,'单位向量余弦相似度','Cosine similarity of unit vectors'],
 neighbors:[['近邻个数 k','Neighbors k',1,4,1,2],null,'查询 2 在 [0,1,2,8,9] 中第 k 邻居的距离','Distance to kth neighbor of query 2 in [0,1,2,8,9]'],
 macro:[['概率阈值','Probability threshold',.05,.95,.05,.5],null,'宏平均 F1（0–1）','Macro F1 (0–1)'],
 knn_deep:[['邻居数 k','Neighbors k',1,5,1,3],['按给定范围缩放：0 否 / 1 是','Range scaling: 0 no / 1 yes',0,1,1,1],'预测标签（0 或 1）','Predicted label (0 or 1)'],
 audit:[['可用分钟','Available minutes',60,300,5,120],['预留核查分钟','Reserve for checks',5,45,5,15],'扣除检查后可作答分钟','Solving minutes after reserving checks']
};
function advancedBi(z,e){return `<span data-bi class="bi-pair"><span class="bi-zh" lang="zh-CN">${E(z)}</span><span class="bi-en" lang="en">${E(e)}</span></span>`}
function renderAdvancedLab(l){const meta=ADVANCED_LABS[l.labType],root=$('#lab');const context={broadcast:['计算 (N,1) 减 (N,) 的广播形状。','Compute broadcasting of (N,1) minus (N,).'],svd:['固定奇异值为 [4,3,2,1]。','Fixed singular values: [4,3,2,1].'],macro:['固定标签 y=[0,0,0,0,1,1,1,1]；概率 p=[0.05,0.2,0.4,0.65,0.3,0.55,0.75,0.9]。p≥阈值时预测 1。','Fixed labels y=[0,0,0,0,1,1,1,1]; probabilities p=[0.05,0.2,0.4,0.65,0.3,0.55,0.75,0.9]. Predict 1 when p≥threshold.'],knn_deep:['训练点 (x1,x2,label) 为 [(0,0,0),(1,10,0),(2,800,1),(3,900,1),(4,1000,1)]；查询点 (1.5,450)。使用欧氏距离、均匀投票，距离并列按原索引。给定缩放范围 [4,1000]。','Training (x1,x2,label): [(0,0,0),(1,10,0),(2,800,1),(3,900,1),(4,1000,1)]; query (1.5,450). Use Euclidean distance and uniform votes, breaking distance ties by original index. Given scaling ranges: [4,1000].'],freeze:['假设骨干含 1,000,000 个参数（仅示例，不是 ResNet 实际数）；分类头输入 1024 维且有偏置。','Assume 1,000,000 backbone parameters (illustrative, not actual ResNet); the head has 1024 inputs and a bias.'],chain:['L=(tanh(wx)−1)²/2，偏置固定为 0。','L=(tanh(wx)−1)²/2, with bias fixed at zero.']}[l.labType];root.innerHTML=`<p>${advancedBi('先手算下面的目标值，再调整参数检验你的理解。误差容许范围为 0.001 或相对误差 0.1%。','Calculate the target first, then vary parameters. Tolerance is 0.001 or 0.1% relative error.')}</p>${context?`<p class="lab-prompt">${advancedBi(...context)}</p>`:''}<div class="lab-controls">${meta.slice(0,2).map((c,i)=>c?`<label>${advancedBi(c[0],c[1])}<input id="advanced${i}" type="range" min="${c[2]}" max="${c[3]}" step="${c[4]}" value="${c[5]}"><output id="advancedValue${i}">${c[5]}</output></label>`:'').join('')}</div><p>${advancedBi(meta[2],meta[3])}</p><label>${advancedBi('你的预测值','Your predicted value')}<input id="advancedGuess" type="number" step="any"></label><div class="lab-buttons"><button id="advancedCheck">${advancedBi('检查预测','Check prediction')}</button><button id="advancedReveal">${advancedBi('查看逐步结果','Show step-by-step results')}</button></div><p id="advancedFeedback" aria-live="polite"></p><div id="advancedResult" hidden></div>`;
let result;const format=v=>typeof v==='number'?(Math.abs(v)<1e-10?'0':Number(v.toPrecision(7)).toString()):String(v);
const update=()=>{let a=Number($('#advanced0').value),b=meta[1]?Number($('#advanced1').value):0;$('#advancedValue0').textContent=a;if(meta[1])$('#advancedValue1').textContent=b;result=AdvancedMath.compute(l.labType,a,b);$('#advancedResult').hidden=true;$('#advancedGuess').value='';$('#advancedFeedback').textContent='';let graphic='';if(result.projection){let p=result.projection;graphic=`<svg viewBox="0 0 360 260" role="img" aria-label="x and its projection"><path d="M30 180H330M30 180V15" stroke="#bac7da" fill="none"/><path d="M30 180L180 80" stroke="#345cdb" stroke-width="3"/><path d="M30 180L${30+p[0]*50} ${180-p[1]*50}" stroke="#12815a" stroke-width="3"/><path d="M180 80L${30+p[0]*50} ${180-p[1]*50}" stroke="#a16d30" stroke-dasharray="4 4"/><text x="185" y="78">x=(3,2)</text></svg>`}if(result.bars)graphic=`<svg viewBox="0 0 360 160" role="img" aria-label="Fourth-power spectral energy">${result.bars.map((v,i)=>`<rect x="${30+i*80}" y="${130-v*.4}" width="45" height="${v*.4}" fill="${i<a?'#345cdb':'#bac7da'}"/><text x="${30+i*80}" y="150">${v}</text>`).join('')}</svg>`;$('#advancedResult').innerHTML=graphic+'<table><tbody>'+result.rows.map(([z,e,v])=>`<tr><th>${advancedBi(z,e)}</th><td>${E(format(v))}</td></tr>`).join('')+'</tbody></table>'};
$('#advanced0').oninput=update;if(meta[1])$('#advanced1').oninput=update;$('#advancedReveal').onclick=()=>{$('#advancedResult').hidden=false};$('#advancedCheck').onclick=()=>{let raw=$('#advancedGuess').value,n=Number(raw);if(raw.trim()===''||!Number.isFinite(n)){$('#advancedFeedback').innerHTML=advancedBi('请输入一个有效数值。','Enter a valid number.');return}let ok=Math.abs(n-result.value)<=Math.max(.001,Math.abs(result.value)*.001);$('#advancedFeedback').innerHTML=ok?advancedBi('✓ 预测正确。改变参数后再试一次。','✓ Correct prediction. Change parameters and try again.'):advancedBi('还不一致。检查公式和分母，或展开结果对照。','Not yet. Check the formula and denominator, or reveal the steps.');if(ok)$('#advancedResult').hidden=false};update();
}
